const fakeResponse = {
  tariff_codes: [
    {
      tariff_code: 480,
      tariff_name: "Экспресс дверь-дверь",
      tariff_description: "Экспресс-доставка",
      delivery_mode: 1,
      delivery_sum: 1515.0,
      period_min: 2,
      period_max: 3,
      calendar_min: 2,
      calendar_max: 3,
    },
    {
      tariff_code: 481,
      tariff_name: "Экспресс дверь-склад",
      tariff_description: "Экспресс-доставка",
      delivery_mode: 2,
      delivery_sum: 1420.0,
      period_min: 2,
      period_max: 3,
      calendar_min: 2,
      calendar_max: 3,
    },
    {
      tariff_code: 482,
      tariff_name: "Экспресс склад-дверь",
      tariff_description: "Экспресс-доставка",
      delivery_mode: 3,
      delivery_sum: 1420.0,
      period_min: 2,
      period_max: 3,
      calendar_min: 2,
      calendar_max: 3,
    },
    {
      tariff_code: 483,
      tariff_name: "Экспресс склад-склад",
      tariff_description: "Экспресс-доставка",
      delivery_mode: 4,
      delivery_sum: 1340.0,
      period_min: 2,
      period_max: 3,
      calendar_min: 2,
      calendar_max: 3,
    },
    {
      tariff_code: 485,
      tariff_name: "Экспресс дверь-постамат",
      tariff_description: "Экспресс-доставка",
      delivery_mode: 6,
      delivery_sum: 1420.0,
      period_min: 2,
      period_max: 3,
      calendar_min: 2,
      calendar_max: 3,
    },
    {
      tariff_code: 486,
      tariff_name: "Экспресс склад-постамат",
      tariff_description: "Экспресс-доставка",
      delivery_mode: 7,
      delivery_sum: 1340.0,
      period_min: 2,
      period_max: 3,
      calendar_min: 2,
      calendar_max: 3,
    },
    {
      tariff_code: 605,
      tariff_name: "Экспресс постамат-дверь",
      tariff_description: "Экспресс-доставка",
      delivery_mode: 8,
      delivery_sum: 1420.0,
      period_min: 2,
      period_max: 3,
      calendar_min: 2,
      calendar_max: 3,
    },
    {
      tariff_code: 606,
      tariff_name: "Экспресс постамат-склад",
      tariff_description: "Экспресс-доставка",
      delivery_mode: 9,
      delivery_sum: 1340.0,
      period_min: 2,
      period_max: 3,
      calendar_min: 2,
      calendar_max: 3,
    },
    {
      tariff_code: 607,
      tariff_name: "Экспресс постамат-постамат",
      tariff_description: "Экспресс-доставка",
      delivery_mode: 10,
      delivery_sum: 1340.0,
      period_min: 2,
      period_max: 3,
      calendar_min: 2,
      calendar_max: 3,
    },
    {
      tariff_code: 121,
      tariff_name: "Магистральный экспресс дверь-дверь",
      tariff_description: "",
      delivery_mode: 1,
      delivery_sum: 2780.0,
      period_min: 4,
      period_max: 5,
      calendar_min: 4,
      calendar_max: 5,
    },
    {
      tariff_code: 123,
      tariff_name: "Магистральный экспресс дверь-склад",
      tariff_description: "",
      delivery_mode: 2,
      delivery_sum: 2230.0,
      period_min: 4,
      period_max: 5,
      calendar_min: 4,
      calendar_max: 5,
    },
    {
      tariff_code: 122,
      tariff_name: "Магистральный экспресс склад-дверь",
      tariff_description: "",
      delivery_mode: 3,
      delivery_sum: 2230.0,
      period_min: 4,
      period_max: 5,
      calendar_min: 4,
      calendar_max: 5,
    },
    {
      tariff_code: 62,
      tariff_name: "Магистральный экспресс склад-склад",
      tariff_description: "",
      delivery_mode: 4,
      delivery_sum: 1680.0,
      period_min: 4,
      period_max: 5,
      calendar_min: 4,
      calendar_max: 5,
    },
    {
      tariff_code: 139,
      tariff_name: "Посылка дверь-дверь",
      tariff_description: "",
      delivery_mode: 1,
      delivery_sum: 960.0,
      period_min: 2,
      period_max: 4,
      calendar_min: 2,
      calendar_max: 4,
    },
    {
      tariff_code: 138,
      tariff_name: "Посылка дверь-склад",
      tariff_description: "",
      delivery_mode: 2,
      delivery_sum: 755.0,
      period_min: 2,
      period_max: 4,
      calendar_min: 2,
      calendar_max: 4,
    },
    {
      tariff_code: 137,
      tariff_name: "Посылка склад-дверь",
      tariff_description: "",
      delivery_mode: 3,
      delivery_sum: 755.0,
      period_min: 2,
      period_max: 4,
      calendar_min: 2,
      calendar_max: 4,
    },
    {
      tariff_code: 136,
      tariff_name: "Посылка склад-склад",
      tariff_description: "",
      delivery_mode: 4,
      delivery_sum: 550.0,
      period_min: 2,
      period_max: 4,
      calendar_min: 2,
      calendar_max: 4,
    },
    {
      tariff_code: 366,
      tariff_name: "Посылка дверь-постамат",
      tariff_description: "",
      delivery_mode: 6,
      delivery_sum: 755.0,
      period_min: 2,
      period_max: 4,
      calendar_min: 2,
      calendar_max: 4,
    },
    {
      tariff_code: 368,
      tariff_name: "Посылка склад-постамат",
      tariff_description: "",
      delivery_mode: 7,
      delivery_sum: 550.0,
      period_min: 2,
      period_max: 4,
      calendar_min: 2,
      calendar_max: 4,
    },
    {
      tariff_code: 748,
      tariff_name: "Сборный груз дверь-дверь",
      tariff_description:
        'Наземная доставка тяжеловесных отправлений, погрузо-разгрузочные работы не включены в тариф.\nДля корректного отображения офисов, обрабатывающих заказы по тарифу "сборный груз" необходимо выбрать доп.тип заказа "сборный груз" \n',
      delivery_mode: 1,
      delivery_sum: 5150.0,
      period_min: 4,
      period_max: 5,
      calendar_min: 4,
      calendar_max: 5,
    },
    {
      tariff_code: 749,
      tariff_name: "Сборный груз дверь-склад",
      tariff_description:
        'Наземная доставка тяжеловесных отправлений, погрузо-разгрузочные работы не включены в тариф.\nДля корректного отображения офисов, обрабатывающих заказы по тарифу "сборный груз" необходимо выбрать доп.тип заказа "сборный груз" \n',
      delivery_mode: 2,
      delivery_sum: 4400.0,
      period_min: 4,
      period_max: 5,
      calendar_min: 4,
      calendar_max: 5,
    },
    {
      tariff_code: 750,
      tariff_name: "Сборный груз склад-дверь",
      tariff_description:
        'Наземная доставка тяжеловесных отправлений, погрузо-разгрузочные работы не включены в тариф.\nДля корректного отображения офисов, обрабатывающих заказы по тарифу "сборный груз" необходимо выбрать доп.тип заказа "сборный груз" \n',
      delivery_mode: 3,
      delivery_sum: 4300.0,
      period_min: 4,
      period_max: 5,
      calendar_min: 4,
      calendar_max: 5,
    },
    {
      tariff_code: 751,
      tariff_name: "Сборный груз склад-склад",
      tariff_description:
        'Наземная доставка тяжеловесных отправлений, погрузо-разгрузочные работы не включены в тариф.\nДля корректного отображения офисов, обрабатывающих заказы по тарифу "сборный груз" необходимо выбрать доп.тип заказа "сборный груз" \n',
      delivery_mode: 4,
      delivery_sum: 3550.0,
      period_min: 4,
      period_max: 5,
      calendar_min: 4,
      calendar_max: 5,
    },
  ],
};
export default fakeResponse;